return {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
    "neovim/nvim-lspconfig",
    "ellisonleao/gruvbox.nvim",
    "stevearc/dressing.nvim",
    "isobit/vim-caddyfile",
    "peterhoeg/vim-qml",
    "williamboman/mason.nvim",
    "williamboman/mason-lspconfig.nvim",
    "jose-elias-alvarez/null-ls.nvim",
    "jayp0521/mason-null-ls.nvim",
    "mfussenegger/nvim-dap",
    "jayp0521/mason-nvim-dap.nvim",
}
