# Don't print a new line at the start of the prompt
add_newline = false

# Prompt
format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$jobs\
$status\
$character
"""

right_format = """
$python\
$container
"""

[directory]
fish_style_pwd_dir_length = 3
truncation_length = 3
style = "cyan"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "yellow"
stashed = "*"

[status]
format = '[\[$status\]]($style) '
style = "red"
disabled = true

[python]
format = '$virtualenv($style)'

[container]
format = '[$symbol $name]($style) '
style = "purple"
